#!/bin/bash
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <inputData> <fromAddress> <toAddress>"
    exit 1
fi
inputData="$1"
fromAddress="$2"
toAddress="$3"
node call.js "$inputData" "$fromAddress" "$toAddress"
