#!/bin/bash
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 <inputData> <fromAddress> <toAddress> <gasLimit>"
    exit 1
fi
inputData="$1"
fromAddress="$2"
toAddress="$3"
gasLimit="$4"
node call.js "$inputData" "$fromAddress" "$toAddress" "$gasLimit"