name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

  # This enables colored output for tests run by `mocha`.
  # `FORCE_COLOR` is used by `chalk`, which is used internally by `mocha`.
  # https://github.com/chalk/chalk#supportscolor
  # https://github.com/orgs/community/discussions/26944#discussioncomment-3254075
  FORCE_COLOR: 3

jobs:
  sol-tests-coverage:
    name: 'Solidity Coverage test'
    runs-on: smart-contracts-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'

      - name: Install Foundry
        uses: step-security/foundry-toolchain@01e2d127ea061e2ce8fa34340de71ca8518f093e # v1.2.1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build

      - name: Mock curl
        run: echo "./test/scripts" >> "$GITHUB_PATH"

      - name: Run Forge Coverage
        run: forge coverage --summary --fork-url https://testnet.hashio.io/api --fork-block-number 13890397 > summary.info

      - name: Public Coverage
        run: cat summary.info | .github/publish.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
